"""Add hex id to accounts

Revision ID: 0df7c210dfbe
Revises: fac0e492e3e7
Create Date: 2024-11-07 13:09:55.416352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df7c210dfbe'
down_revision: Union[str, None] = 'fac0e492e3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_id', table_name='accounts')
    op.drop_index('ix_accounts_login', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_auth_id', table_name='auth')
    op.drop_index('ix_auth_login', table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('login', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('scopes', sa.VARCHAR(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_login', 'auth', ['login'], unique=1)
    op.create_index('ix_auth_id', 'auth', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('login', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_login', 'accounts', ['login'], unique=1)
    op.create_index('ix_accounts_id', 'accounts', ['id'], unique=False)
    # ### end Alembic commands ###
