version: '3.8'

services:
  api:
    image: python:3.10
    container_name: starnavi_test_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_API_PORT}:${APP_API_PORT}"
    volumes:
      - .:/app
    environment:
      PYTHONPATH: .
      TZ: UTC
    env_file:
      - .env
    networks:
      - starnavi_network
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:14.2
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      TZ: UTC
      APP_API_PORT: ${APP_API_PORT}
      APP_CONFIG_FILE: app/config.yaml
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - starnavi_network
    env_file:
      - .env

networks:
  starnavi_network:
    driver: bridge