version: '3.8'

services:
  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - starnavi_network
    env_file: .env
    command: sh -c "alembic upgrade head && pytest"

  db:
    image: postgres:14.2
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - starnavi_network
    env_file:
      - .env

networks:
  starnavi_network:
    driver: bridge