db:
  master: !ENV ${ASYNC_DATABASE_URL}
  master_pool_min_size: !ENV ${MIN_POOL_SIZE:2}
  master_pool_max_size: !ENV ${MAX_POOL_SIZE:5}
env:
  port: !ENV ${APP_API_PORT}
  enable_cors: false
  debug: true
auth:
  secret_key: !ENV ${AUTH_SECRET_KEY}
  algorithm: 'HS256'
  token_expiration_minutes: 30