db:
  master: !ENV postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  master_sync: !ENV postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  master_pool_min_size: !ENV ${MIN_POOL_SIZE:2}
  master_pool_max_size: !ENV ${MAX_POOL_SIZE:5}
env:
  port: !ENV ${APP_API_PORT}
  enable_cors: false
  debug: true
auth:
  secret_key: !ENV ${AUTH_SECRET_KEY}
  algorithm: 'HS256'
  token_expiration_minutes: 30
gemini:
  api_key: !ENV ${GEMINI_API_KEY}
  generation_config:
    temperature: 0.8
    topP: 0.95
    topK: 45
    maxOutputTokens: 256